FIX: Add missing SITE argument to setup-environment

diff --git a/scripts/linux/installation/setup-environment b/scripts/linux/installation/setup-environment
--- a/scripts/linux/installation/setup-environment
+++ b/scripts/linux/installation/setup-environment
@@ -1,5 +1,14 @@
 #!/bin/bash
 
+# Get the site from the first argument
+SITE="$1"
+
+if [ -z "$SITE" ]; then
+    echo "Error: Site is undefined. Please provide it as an argument to the script."
+    echo ""
+    exit 1
+fi
+
 # Set the site in .bashrc
 if ! grep -q "export SITE=$SITE" ~/.bashrc; then
     echo "export SITE=$SITE" >> ~/.bashrc
