MOD: Improve and robustify MATLAB message build script

diff --git a/scripts/build-mtms-matlab b/scripts/build-mtms-matlab
--- a/scripts/build-mtms-matlab
+++ b/scripts/build-mtms-matlab
@@ -12,32 +12,29 @@ RESET=$(tput sgr0)
 echo "  • ${BOLD}Building the MATLAB interfaces...${RESET}"
 
 # Create a temporary directory for all the interfaces
-mkdir -p /home/mtms/mtms/ros2_ws/src/temp_interfaces
-ln -s /home/mtms/mtms/ros2_ws/src/shared_packages/interfaces/* /home/mtms/mtms/ros2_ws/src/temp_interfaces/
-ln -s /home/mtms/mtms/ros2_ws/src/mtms_packages/interfaces/* /home/mtms/mtms/ros2_ws/src/temp_interfaces/
+mkdir -p $MTMS_ROOT/ros2_ws/src/temp_interfaces
+ln -s $MTMS_ROOT/ros2_ws/src/shared_packages/interfaces/* $MTMS_ROOT/ros2_ws/src/temp_interfaces/
+ln -s $MTMS_ROOT/ros2_ws/src/mtms_packages/interfaces/* $MTMS_ROOT/ros2_ws/src/temp_interfaces/
 
 # Generate the MATLAB message files
 matlab -nodisplay -nosplash -nodesktop -r " \
 ros2genmsg('/home/mtms/mtms/ros2_ws/src/temp_interfaces', 'CreateShareableFile', true, 'BuildConfiguration', 'fasterruns'); \
 exit;"
 
-# Check if the .zip file exists and then move it
-if [ -f "$MTMS_ROOT/ros2_ws/src/temp_interfaces/matlab_msg_gen.zip" ]; then
-    mv "$MTMS_ROOT/ros2_ws/src/temp_interfaces/matlab_msg_gen.zip" "$MTMS_ROOT/api/matlab/"
-else
-    echo "matlab_msg_gen.zip does not exist."
+if [ $? -ne 0 ]; then
+    echo "Error: MATLAB failed to generate the message files."
+
+    # Remove the temporary directory
+    rm -rf $MTMS_ROOT/ros2_ws/src/temp_interfaces
+
+    exit 1
 fi
 
-# Delete the matlab_msg_gen directory
-if [ -d "$MTMS_ROOT/ros2_ws/src/temp_interfaces/matlab_msg_gen" ]; then
-    rm -rf "$MTMS_ROOT/ros2_ws/src/temp_interfaces/matlab_msg_gen"
-else
-    echo "matlab_msg_gen directory does not exist."
-fi
+# Move the generated MATLAB message files to the API directory
+mv "$MTMS_ROOT/ros2_ws/src/temp_interfaces/matlab_msg_gen.zip" "$MTMS_ROOT/api/matlab/"
 
 # Remove the temporary directory
-rm -rf /home/mtms/mtms/ros2_ws/src/temp_interfaces
-
+rm -rf $MTMS_ROOT/ros2_ws/src/temp_interfaces
 
 echo "  • ${BOLD}Registering the MATLAB interfaces...${RESET}"
 
